export enum EnrollmentStatus {
  PENDING = 'PENDING',
  WAITLISTED = 'WAITLISTED',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  DROPPED = 'DROPPED',
  COMPLETED = 'COMPLETED',
}